Repository openfed/openfed, pull requests merged in 2024-02, with the labels that each got.

#63 OPENFED-39: Fix File URL alias status issue
  config/install/pathauto.settings.yml
  openfed.install
Labels: bug

#66 OPENFED-20: Fix encoding on file entity
  composer.json
  composer.lock
  config/install/user.role.anonymous.yml
  config/install/user.role.authenticated.yml
  config/install/user.role.content_editor.yml
  config/install/views.view.files.yml
  modules/openfed_features/openfed_file_entity/config/optional/field.field.file.image.field_image_alt_text.yml
  modules/openfed_features/openfed_file_entity/config/optional/field.field.file.image.field_image_title_text.yml
  modules/openfed_features/openfed_file_entity/config/optional/file_entity.type.other.yml
  modules/openfed_features/openfed_file_entity/config/optional/openfed_multilingual.language.content_settings.file.audio.yml
  modules/openfed_features/openfed_file_entity/config/optional/openfed_multilingual.language.content_settings.file.document.yml
  modules/openfed_features/openfed_file_entity/config/optional/openfed_multilingual.language.content_settings.file.image.yml
  modules/openfed_features/openfed_file_entity/config/optional/openfed_multilingual.language.content_settings.file.other.yml
  modules/openfed_features/openfed_file_entity/config/optional/openfed_multilingual.language.content_settings.file.video.yml
  modules/openfed_features/openfed_file_entity/openfed_file_entity.info.yml
  modules/openfed_features/openfed_file_entity/openfed_file_entity.install
  openfed.info.yml
  openfed.install
Labels: bug, enhancement

#67 Feature/openfed 26 double file views
  config/install/views.view.files.yml
  modules/openfed_features/openfed_file_entity/openfed_file_entity.module
Labels: enhancement

#69 #68: Update patch for menu_link module.
  composer.json
Labels: bug
